# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Postbacks',
        ),
        migrations.RenameField(
            model_name='postbacks',
            old_name='rating',
            new_name='postback',
        ),
    ]
